[config]
schemaVersion = "0.0.1"

[package]
namespace = "DesktopBuddy"
name = "CustomEverything"
versionNumber = "0.1.0"
description = "Personal UI customization experiments for Resonite, starting with custom inspectors and ProtoFlux browsers."
websiteUrl = "https://github.com/DevL0rd/CustomEverything"
containsNsfwContent = false

[package.dependencies]
ResoniteModding-BepisLoader = "1.6.0"
ResoniteModding-BepisResoniteWrapper = "1.0.2"

[build]
icon = "./icon.png"
readme = "./README_THUNDERSTORE.md"
outdir = "./build"

[[build.copy]]
source = "./CustomEverything/bin/Release/net10.0-windows10.0.26100.0/CustomEverything.dll"
target = "plugins/CustomEverything/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = ["mods"]
